### ISSUE TITLE
[Question] Lazy load will make this plugin not work?

### ISSUE THREAD

**Issue by tan-wei** [VidocqH/auto-indent.nvim#5]
I try to make it lazy load with `lazy.nvim` with the following options:
  - `event = "VeryLazy"`
  - `event = "InsertEnter"`

And I can confirm that the plugin will not work. Is it required that the plugin should be always loaded? Thanks.

**Comment by tan-wei** [comment]
Another question: does it will make `tabout.nvim` (or similar function) not function? How to make them work together? Thanks.

**Comment by baizeyv** [comment]
auto-indent.nvim 这个插件看源码根本上是在BufRead的时候进行一次imap绑定,我虽然不用tabout.nvim这个插件，但可想而知tabout肯定也是设置了imap绑定。我的问题是cmp-snippet 这个的<TAB>和auto-indent的冲突。我认为您的tabout问题应该和我解决cmp这个的冲突有些相似，下边是我处理这个<TAB> 的imap冲突问题的截图，但可能这个方案有点蠢，因为这个解决方法需要处理所有的imap绑定了<TAB>的内容,

[The auto-indent.nvim plugin basically performs an imap binding when BufRead is used. Although I don't use the tabout.nvim plugin, it is conceivable that tabout must also have an imap binding. My problem is the conflict between cmp-snippet and auto-indent. I think your tabout problem should be similar to the conflict I solved with cmp. Below is a screenshot of how I solved the imap conflict problem. But this solution may be a bit stupid because it needs to handle all the imap-bound content.]

![hand](https://github.com/VidocqH/auto-indent.nvim/assets/76252320/1b2f0244-595f-490f-b226-a44b716ef7db)
对于延迟加载，auto-indent确实不太行，而且在绑定<TAB>的function中不能直接用nvim_put来写入，只能直接return 字符串。我这里是把auto-indent直接作为了cmp的依赖来加载，这样已经能达到我想要的效果了。我觉得也对您有用.

[For delayed loading, auto-indent is not very good, and you can't use nvim_put to write directly in the bound function, you can only return the string directly. Here I load auto-indent directly as a dependency of cmp, which has achieved the effect I want. I think it will be useful to you too.]

**Comment by tan-wei** [comment]
@baizeyv 谢谢，回头我研究下，听起来很复杂……
